//picks
crafting.remove('minecraft:wooden_pickaxe')
crafting.remove('minecraft:stone_pickaxe')
crafting.remove('minecraft:diamond_pickaxe')
crafting.remove('minecraft:golden_pickaxe')
crafting.remove('appliedenergistics2:tools/certus_quartz_pickaxe')
crafting.remove('appliedenergistics2:tools/nether_quartz_pickaxe')
crafting.remove('enderio:end_pickaxe')
crafting.remove('forestry:bronze_pickaxe')
crafting.remove('forestry:pickaxe_kit')
crafting.remove('galacticraftplanets:desh_pick')
// crafting.remove('galacticraftplanets:desh_pick_slime')
crafting.remove('galacticraftplanets:titanium_pickaxe')
// crafting.remove('galacticraftplanets:volcanic_pickaxe')
crafting.remove('galaxyspace:cobalt_pickaxe')
// crafting.remove('galaxyspace:plasma_pickaxe')
crafting.remove('natura:tools/nether/ghostwood/ghostwood_pickaxe')
crafting.remove('natura:tools/nether/bloodwood/bloodwood_pickaxe')
crafting.remove('natura:tools/nether/darkwood/darkwood_pickaxe')
crafting.remove('natura:tools/nether/ghostwood/fusewood_pickaxe')
crafting.remove('natura:tools/nether/netherquartz/netherquartz_pickaxe')
crafting.remove('projectred-exploration:tools/ruby_pickaxe')
crafting.remove('projectred-exploration:tools/sapphire_pickaxe')
crafting.remove('projectred-exploration:tools/peridot_pickaxe')
crafting.remove('randomthings:spectrepickaxe')

// axe
crafting.remove('minecraft:wooden_axe')
crafting.remove('minecraft:stone_axe')
crafting.remove('minecraft:diamond_axe')
crafting.remove('minecraft:golden_axe')
crafting.remove('appliedenergistics2:tools/certus_quartz_axe')
crafting.remove('appliedenergistics2:tools/nether_quartz_axe')
crafting.remove('enderio:end_axe')
crafting.remove('galacticraftplanets:desh_axe')
// crafting.remove('galacticraftplanets:desh_pick_slime')
crafting.remove('galacticraftplanets:titanium_axe')
// crafting.remove('galacticraftplanets:volcanic_pickaxe')
crafting.remove('galaxyspace:cobalt_axe')
// crafting.remove('galaxyspace:plasma_pickaxe')
crafting.remove('natura:tools/nether/ghostwood/ghostwood_axe')
crafting.remove('natura:tools/nether/bloodwood/bloodwood_axe')
crafting.remove('natura:tools/nether/darkwood/darkwood_axe')
crafting.remove('natura:tools/nether/ghostwood/fusewood_axe')
crafting.remove('natura:tools/nether/netherquartz/netherquartz_axe')
crafting.remove('projectred-exploration:tools/ruby_axe')
crafting.remove('projectred-exploration:tools/sapphire_axe')
crafting.remove('projectred-exploration:tools/peridot_axe')
crafting.remove('randomthings:spectrepickaxe')

//shovels
crafting.remove('minecraft:iron_shovel')
crafting.remove('minecraft:wooden_shovel')
crafting.remove('minecraft:stone_shovel')
crafting.remove('minecraft:diamond_shovel')
crafting.remove('minecraft:golden_shovel')
crafting.remove('appliedenergistics2:tools/certus_quartz_spade')
crafting.remove('appliedenergistics2:tools/nether_quartz_spade')
crafting.remove('forestry:bronze_shovel')
crafting.remove('forestry:shovel_kit')
crafting.remove('galacticraftcore:steel_shovel')
crafting.remove('galacticraftplanets:desh_spade')
crafting.remove('galacticraftplanets:titanium_shovel')
crafting.remove('natura:tools/nether/ghostwood/ghostwood_shovel')
crafting.remove('natura:tools/nether/bloodwood/bloodwood_shovel')
crafting.remove('natura:tools/nether/darkwood/darkwood_shovel')
crafting.remove('natura:tools/nether/fusewood/fusewood_shovel')
crafting.remove('natura:tools/nether/netherquartz/netherquartz_shovel')
crafting.remove('projectred-exploration:tools/ruby_shovel')
crafting.remove('projectred-exploration:tools/sapphire_shovel')
crafting.remove('projectred-exploration:tools/peridot_shovel')
crafting.remove('randomthings:spectreshovel')

//swords
crafting.remove('minecraft:iron_sword')
crafting.remove('minecraft:wooden_sword')
crafting.remove('minecraft:stone_sword')
crafting.remove('minecraft:diamond_sword')
crafting.remove('minecraft:golden_sword')
crafting.remove('appliedenergistics2:tools/certus_quartz_sword')
crafting.remove('appliedenergistics2:tools/nether_quartz_sword')
crafting.remove('galacticraftcore:steel_sword')
crafting.remove('galacticraftplanets:desh_sword')
crafting.remove('galacticraftplanets:titanium_sword')
crafting.remove('galaxyspace:cobalt_sword')
// crafting.remove('galaxyspace:plasma_sword')
crafting.remove('natura:tools/nether/ghostwood/ghostwood_sword')
crafting.remove('natura:tools/nether/bloodwood/bloodwood_sword')
crafting.remove('natura:tools/nether/darkwood/darkwood_sword')
crafting.remove('natura:tools/nether/fusewood/fusewood_sword')
crafting.remove('natura:tools/nether/netherquartz/netherquartz_sword')
crafting.remove('projectred-exploration:tools/ruby_sword')
crafting.remove('projectred-exploration:tools/sapphire_sword')
crafting.remove('projectred-exploration:tools/peridot_sword')
crafting.remove('randomthings:spectresword')

//hoes
crafting.remove('minecraft:wooden_hoe')
crafting.remove('minecraft:stone_hoe')
crafting.remove('minecraft:iron_hoe')
crafting.remove('minecraft:diamond_hoe')
crafting.remove('minecraft:golden_hoe')
crafting.remove('appliedenergistics2:tools/certus_quartz_hoe')
crafting.remove('appliedenergistics2:tools/nether_quartz_hoe')
crafting.remove('galacticraftcore:steel_hoe')
crafting.remove('galacticraftplanets:desh_hoe')
crafting.remove('galacticraftplanets:titanium_hoe')
crafting.remove('galaxyspace:cobalt_hoe')
crafting.remove('projectred-exploration:tools/ruby_hoe')
crafting.remove('projectred-exploration:tools/sapphire_hoe')
crafting.remove('projectred-exploration:tools/peridot_hoe')

crafting.remove('claybucket:unfiredclaybucket')
crafting.addShaped('unfiredclaybucket', item('claybucket:unfiredclaybucket') * 1, [
    [ore('dustClay'), null, ore('dustClay')],
    [ore('dustClay'), ore('dustClay'), ore('dustClay')]
    ]
)